package ink.fdq.snowy.model.table;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by snowy, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping(ChinaAreas.TABLE_NAME, ChinaAreas.PK_NAME, ChinaAreas.class);
		arp.addMapping(UserInfo.TABLE_NAME, UserInfo.PK_NAME, UserInfo.class);
		arp.addMapping(WebConfig.TABLE_NAME, WebConfig.PK_NAME, WebConfig.class);
	}
}

