package ink.fdq.snowy.core.model.table;

import ink.fdq.snowy.core.model.table.base.BaseSysResc;
/**
 * Generated by snowy.
 */
@SuppressWarnings("serial")
public class SysResc extends BaseSysResc<SysResc> {

}
