package ink.fdq.snowy.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by snowy, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleResc<M extends BaseSysRoleResc<M>> extends Model<M> implements IBean {

    /**
     * 表名
     */
    public final static String TABLE_NAME = "snowy_sys_role_resc";

    /**
     * 主键
     */
    public final static String PK_NAME = "id";

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	public void setRescId(java.lang.Integer rescId) {
		set("resc_id", rescId);
	}
	
	public java.lang.Integer getRescId() {
		return getInt("resc_id");
	}

}
