package ink.fdq.snowy.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by snowy, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

    /**
     * 表名
     */
    public final static String TABLE_NAME = "snowy_user_info";

    /**
     * 主键
     */
    public final static String PK_NAME = "id";

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setWebsite(java.lang.String website) {
		set("website", website);
	}
	
	public java.lang.String getWebsite() {
		return getStr("website");
	}

	public void setSha(java.lang.String sha) {
		set("sha", sha);
	}
	
	public java.lang.String getSha() {
		return getStr("sha");
	}

	public void setShaPassword(java.lang.String shaPassword) {
		set("sha_password", shaPassword);
	}
	
	public java.lang.String getShaPassword() {
		return getStr("sha_password");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}

	public void setHeadPhotoPath(java.lang.String headPhotoPath) {
		set("head_photo_path", headPhotoPath);
	}
	
	public java.lang.String getHeadPhotoPath() {
		return getStr("head_photo_path");
	}

	public void setSignature(java.lang.String signature) {
		set("signature", signature);
	}
	
	public java.lang.String getSignature() {
		return getStr("signature");
	}

	public void setUserStatus(java.lang.String userStatus) {
		set("user_status", userStatus);
	}
	
	public java.lang.String getUserStatus() {
		return getStr("user_status");
	}

	public void setUserType(java.lang.String userType) {
		set("user_type", userType);
	}
	
	public java.lang.String getUserType() {
		return getStr("user_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}
	
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	public void setLastLoginCountry(java.lang.String lastLoginCountry) {
		set("last_login_country", lastLoginCountry);
	}
	
	public java.lang.String getLastLoginCountry() {
		return getStr("last_login_country");
	}

	public void setLastLoginProvince(java.lang.String lastLoginProvince) {
		set("last_login_province", lastLoginProvince);
	}
	
	public java.lang.String getLastLoginProvince() {
		return getStr("last_login_province");
	}

	public void setLastLoginCity(java.lang.String lastLoginCity) {
		set("last_login_city", lastLoginCity);
	}
	
	public java.lang.String getLastLoginCity() {
		return getStr("last_login_city");
	}

}
