package ink.fdq.snowy.core.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by snowy, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChinaAreas<M extends BaseChinaAreas<M>> extends Model<M> implements IBean {

    /**
     * 表名
     */
    public final static String TABLE_NAME = "snowy_china_areas";

    /**
     * 主键
     */
    public final static String PK_NAME = "id";

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPId(java.lang.Long pId) {
		set("p_id", pId);
		return (M)this;
	}
	
	public java.lang.Long getPId() {
		return getLong("p_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
		return (M)this;
	}
	
	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

}
