package ink.fdq.snowy.core.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by snowy, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

    /**
     * 表名
     */
    public final static String TABLE_NAME = "snowy_user_info";

    /**
     * 主键
     */
    public final static String PK_NAME = "user_id";

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	public M setShaValue(java.lang.String shaValue) {
		set("sha_value", shaValue);
		return (M)this;
	}
	
	public java.lang.String getShaValue() {
		return getStr("sha_value");
	}

	public M setShaPassword(java.lang.String shaPassword) {
		set("sha_password", shaPassword);
		return (M)this;
	}
	
	public java.lang.String getShaPassword() {
		return getStr("sha_password");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}
	
	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserAvatar(java.lang.String userAvatar) {
		set("user_avatar", userAvatar);
		return (M)this;
	}
	
	public java.lang.String getUserAvatar() {
		return getStr("user_avatar");
	}

	public M setUserSignature(java.lang.String userSignature) {
		set("user_signature", userSignature);
		return (M)this;
	}
	
	public java.lang.String getUserSignature() {
		return getStr("user_signature");
	}

	public M setLoginStatus(java.lang.String loginStatus) {
		set("login_status", loginStatus);
		return (M)this;
	}
	
	public java.lang.String getLoginStatus() {
		return getStr("login_status");
	}

	public M setUserStatus(java.lang.Integer userStatus) {
		set("user_status", userStatus);
		return (M)this;
	}
	
	public java.lang.Integer getUserStatus() {
		return getInt("user_status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
		return (M)this;
	}
	
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	public M setLastLoginCountry(java.lang.String lastLoginCountry) {
		set("last_login_country", lastLoginCountry);
		return (M)this;
	}
	
	public java.lang.String getLastLoginCountry() {
		return getStr("last_login_country");
	}

	public M setLastLoginProvince(java.lang.String lastLoginProvince) {
		set("last_login_province", lastLoginProvince);
		return (M)this;
	}
	
	public java.lang.String getLastLoginProvince() {
		return getStr("last_login_province");
	}

	public M setLastLoginCity(java.lang.String lastLoginCity) {
		set("last_login_city", lastLoginCity);
		return (M)this;
	}
	
	public java.lang.String getLastLoginCity() {
		return getStr("last_login_city");
	}

}
